server:
  port: 8088

spring:
  application:
    name: integration-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:sureshkundan913@gmail.com}
    password: ${MAIL_PASSWORD:jkcv gknw zwoc wuwa}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
