apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crm-tls
  namespace: kd
spec:
  secretName: crm-tls-secret

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
  - crm.kundanluziana.in
