apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discovery-server

  - auth-service
  - api-gateway

  - customer-service
  - sales-service
  - marketing-service
  - support-service
  - analytics-service
  - workflow-service
  - integration-service
  - notification-service

  - frontend
