apiVersion: v1
kind: Service

metadata:
  name: customer-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  selector:
    app: customer-service

  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP

  type: ClusterIP
