apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: marketing-service-hpa
  namespace: kd

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marketing-service

  minReplicas: 1
  maxReplicas: 2

  metrics:
  - type: Resource
    resource:
      name: cpu

      target:
        type: Utilization
        averageUtilization: 70
