apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: crm-prod
  namespace: argocd

spec:
  project: crm-platform

  source:
    repoURL: https://github.com/Kdmodder/crm-multi-env-gitops.git
    targetRevision: main
    path: kubernetes/overlays/prod
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: crm-prod
