apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: crm-image-updater
  namespace: argocd

spec:
  applicationRefs:
    - namePattern: "crm-app"
      useAnnotations: true

  writeBackConfig:
    method: git
