apiVersion: v1 # Specifies the API version for Kubernetes resources
kind: Secret # Declares that this resource is a Secret
metadata:
  name: docker-personal-access-token # Name of the Secret object
  namespace: argocd # Namespace where the Secret will be created
stringData:
  username: "kdmodder" # Your Docker  username for authentication
  password: "" # Your Docker personal access token for authentication
