apiVersion: v1
kind: Service

metadata:
  name: workflow-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  selector:
    app: workflow-service

  ports:
    - name: http
      port: 8087
      targetPort: 8087
      protocol: TCP

  type: ClusterIP
