name: discovery-server CI/CD

on:
  push:
    branches:
      - staging
    paths:
      - 'services/discovery-server/**'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

    with:
      service: discovery-server
      service_path: services/discovery-server

    secrets: inherit
