name: sales-service CI/CD

on:
  push:
    branches:
      - staging
    paths:
      - 'services/sales-service/**'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

    with:
      service: sales-service
      service_path: services/sales-service

    secrets: inherit
